run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - gosimple
    - gofmt
    - goimports
    - deadcode

issues:
  exclude-rules:
    - path: _test\.go

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
