version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
  exclusions:
    rules:
      - path: _test\.go
        text: ".*"

formatters:
  enable:
    - gofmt
    - goimports
