// Code generated by scripts, DO NOT EDIT.

package tuples

import (
	"sync/atomic"

	"github.com/jizhuozhi/go-future"
)

// Of2 waits for 2 Futures of unrelated types and resolves with a Tuple2.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of2[T0, T1 any](t0 *future.Future[T0], t1 *future.Future[T1]) *future.Future[Tuple2[T0, T1]] {
	var done uint32
	p := future.NewPromise[Tuple2[T0, T1]]()
	c := int32(2)

	var res0 T0
	var res1 T1

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple2[T0, T1]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple2[T0, T1]{res0, res1}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})

	return p.Future()
}

// Of3 waits for 3 Futures of unrelated types and resolves with a Tuple3.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of3[T0, T1, T2 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2]) *future.Future[Tuple3[T0, T1, T2]] {
	var done uint32
	p := future.NewPromise[Tuple3[T0, T1, T2]]()
	c := int32(3)

	var res0 T0
	var res1 T1
	var res2 T2

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple3[T0, T1, T2]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple3[T0, T1, T2]{res0, res1, res2}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})

	return p.Future()
}

// Of4 waits for 4 Futures of unrelated types and resolves with a Tuple4.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of4[T0, T1, T2, T3 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2], t3 *future.Future[T3]) *future.Future[Tuple4[T0, T1, T2, T3]] {
	var done uint32
	p := future.NewPromise[Tuple4[T0, T1, T2, T3]]()
	c := int32(4)

	var res0 T0
	var res1 T1
	var res2 T2
	var res3 T3

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple4[T0, T1, T2, T3]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple4[T0, T1, T2, T3]{res0, res1, res2, res3}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})
	t3.Subscribe(func(val T3, err error) {
		res3 = val
		cb(err)
	})

	return p.Future()
}

// Of5 waits for 5 Futures of unrelated types and resolves with a Tuple5.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of5[T0, T1, T2, T3, T4 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2], t3 *future.Future[T3], t4 *future.Future[T4]) *future.Future[Tuple5[T0, T1, T2, T3, T4]] {
	var done uint32
	p := future.NewPromise[Tuple5[T0, T1, T2, T3, T4]]()
	c := int32(5)

	var res0 T0
	var res1 T1
	var res2 T2
	var res3 T3
	var res4 T4

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple5[T0, T1, T2, T3, T4]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple5[T0, T1, T2, T3, T4]{res0, res1, res2, res3, res4}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})
	t3.Subscribe(func(val T3, err error) {
		res3 = val
		cb(err)
	})
	t4.Subscribe(func(val T4, err error) {
		res4 = val
		cb(err)
	})

	return p.Future()
}

// Of6 waits for 6 Futures of unrelated types and resolves with a Tuple6.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of6[T0, T1, T2, T3, T4, T5 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2], t3 *future.Future[T3], t4 *future.Future[T4], t5 *future.Future[T5]) *future.Future[Tuple6[T0, T1, T2, T3, T4, T5]] {
	var done uint32
	p := future.NewPromise[Tuple6[T0, T1, T2, T3, T4, T5]]()
	c := int32(6)

	var res0 T0
	var res1 T1
	var res2 T2
	var res3 T3
	var res4 T4
	var res5 T5

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple6[T0, T1, T2, T3, T4, T5]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple6[T0, T1, T2, T3, T4, T5]{res0, res1, res2, res3, res4, res5}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})
	t3.Subscribe(func(val T3, err error) {
		res3 = val
		cb(err)
	})
	t4.Subscribe(func(val T4, err error) {
		res4 = val
		cb(err)
	})
	t5.Subscribe(func(val T5, err error) {
		res5 = val
		cb(err)
	})

	return p.Future()
}

// Of7 waits for 7 Futures of unrelated types and resolves with a Tuple7.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of7[T0, T1, T2, T3, T4, T5, T6 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2], t3 *future.Future[T3], t4 *future.Future[T4], t5 *future.Future[T5], t6 *future.Future[T6]) *future.Future[Tuple7[T0, T1, T2, T3, T4, T5, T6]] {
	var done uint32
	p := future.NewPromise[Tuple7[T0, T1, T2, T3, T4, T5, T6]]()
	c := int32(7)

	var res0 T0
	var res1 T1
	var res2 T2
	var res3 T3
	var res4 T4
	var res5 T5
	var res6 T6

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple7[T0, T1, T2, T3, T4, T5, T6]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple7[T0, T1, T2, T3, T4, T5, T6]{res0, res1, res2, res3, res4, res5, res6}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})
	t3.Subscribe(func(val T3, err error) {
		res3 = val
		cb(err)
	})
	t4.Subscribe(func(val T4, err error) {
		res4 = val
		cb(err)
	})
	t5.Subscribe(func(val T5, err error) {
		res5 = val
		cb(err)
	})
	t6.Subscribe(func(val T6, err error) {
		res6 = val
		cb(err)
	})

	return p.Future()
}

// Of8 waits for 8 Futures of unrelated types and resolves with a Tuple8.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of8[T0, T1, T2, T3, T4, T5, T6, T7 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2], t3 *future.Future[T3], t4 *future.Future[T4], t5 *future.Future[T5], t6 *future.Future[T6], t7 *future.Future[T7]) *future.Future[Tuple8[T0, T1, T2, T3, T4, T5, T6, T7]] {
	var done uint32
	p := future.NewPromise[Tuple8[T0, T1, T2, T3, T4, T5, T6, T7]]()
	c := int32(8)

	var res0 T0
	var res1 T1
	var res2 T2
	var res3 T3
	var res4 T4
	var res5 T5
	var res6 T6
	var res7 T7

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple8[T0, T1, T2, T3, T4, T5, T6, T7]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple8[T0, T1, T2, T3, T4, T5, T6, T7]{res0, res1, res2, res3, res4, res5, res6, res7}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})
	t3.Subscribe(func(val T3, err error) {
		res3 = val
		cb(err)
	})
	t4.Subscribe(func(val T4, err error) {
		res4 = val
		cb(err)
	})
	t5.Subscribe(func(val T5, err error) {
		res5 = val
		cb(err)
	})
	t6.Subscribe(func(val T6, err error) {
		res6 = val
		cb(err)
	})
	t7.Subscribe(func(val T7, err error) {
		res7 = val
		cb(err)
	})

	return p.Future()
}

// Of9 waits for 9 Futures of unrelated types and resolves with a Tuple9.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of9[T0, T1, T2, T3, T4, T5, T6, T7, T8 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2], t3 *future.Future[T3], t4 *future.Future[T4], t5 *future.Future[T5], t6 *future.Future[T6], t7 *future.Future[T7], t8 *future.Future[T8]) *future.Future[Tuple9[T0, T1, T2, T3, T4, T5, T6, T7, T8]] {
	var done uint32
	p := future.NewPromise[Tuple9[T0, T1, T2, T3, T4, T5, T6, T7, T8]]()
	c := int32(9)

	var res0 T0
	var res1 T1
	var res2 T2
	var res3 T3
	var res4 T4
	var res5 T5
	var res6 T6
	var res7 T7
	var res8 T8

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple9[T0, T1, T2, T3, T4, T5, T6, T7, T8]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple9[T0, T1, T2, T3, T4, T5, T6, T7, T8]{res0, res1, res2, res3, res4, res5, res6, res7, res8}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})
	t3.Subscribe(func(val T3, err error) {
		res3 = val
		cb(err)
	})
	t4.Subscribe(func(val T4, err error) {
		res4 = val
		cb(err)
	})
	t5.Subscribe(func(val T5, err error) {
		res5 = val
		cb(err)
	})
	t6.Subscribe(func(val T6, err error) {
		res6 = val
		cb(err)
	})
	t7.Subscribe(func(val T7, err error) {
		res7 = val
		cb(err)
	})
	t8.Subscribe(func(val T8, err error) {
		res8 = val
		cb(err)
	})

	return p.Future()
}

// Of10 waits for 10 Futures of unrelated types and resolves with a Tuple10.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of10[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2], t3 *future.Future[T3], t4 *future.Future[T4], t5 *future.Future[T5], t6 *future.Future[T6], t7 *future.Future[T7], t8 *future.Future[T8], t9 *future.Future[T9]) *future.Future[Tuple10[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9]] {
	var done uint32
	p := future.NewPromise[Tuple10[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9]]()
	c := int32(10)

	var res0 T0
	var res1 T1
	var res2 T2
	var res3 T3
	var res4 T4
	var res5 T5
	var res6 T6
	var res7 T7
	var res8 T8
	var res9 T9

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple10[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple10[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9]{res0, res1, res2, res3, res4, res5, res6, res7, res8, res9}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})
	t3.Subscribe(func(val T3, err error) {
		res3 = val
		cb(err)
	})
	t4.Subscribe(func(val T4, err error) {
		res4 = val
		cb(err)
	})
	t5.Subscribe(func(val T5, err error) {
		res5 = val
		cb(err)
	})
	t6.Subscribe(func(val T6, err error) {
		res6 = val
		cb(err)
	})
	t7.Subscribe(func(val T7, err error) {
		res7 = val
		cb(err)
	})
	t8.Subscribe(func(val T8, err error) {
		res8 = val
		cb(err)
	})
	t9.Subscribe(func(val T9, err error) {
		res9 = val
		cb(err)
	})

	return p.Future()
}

// Of11 waits for 11 Futures of unrelated types and resolves with a Tuple11.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of11[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2], t3 *future.Future[T3], t4 *future.Future[T4], t5 *future.Future[T5], t6 *future.Future[T6], t7 *future.Future[T7], t8 *future.Future[T8], t9 *future.Future[T9], t10 *future.Future[T10]) *future.Future[Tuple11[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]] {
	var done uint32
	p := future.NewPromise[Tuple11[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]]()
	c := int32(11)

	var res0 T0
	var res1 T1
	var res2 T2
	var res3 T3
	var res4 T4
	var res5 T5
	var res6 T6
	var res7 T7
	var res8 T8
	var res9 T9
	var res10 T10

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple11[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple11[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]{res0, res1, res2, res3, res4, res5, res6, res7, res8, res9, res10}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})
	t3.Subscribe(func(val T3, err error) {
		res3 = val
		cb(err)
	})
	t4.Subscribe(func(val T4, err error) {
		res4 = val
		cb(err)
	})
	t5.Subscribe(func(val T5, err error) {
		res5 = val
		cb(err)
	})
	t6.Subscribe(func(val T6, err error) {
		res6 = val
		cb(err)
	})
	t7.Subscribe(func(val T7, err error) {
		res7 = val
		cb(err)
	})
	t8.Subscribe(func(val T8, err error) {
		res8 = val
		cb(err)
	})
	t9.Subscribe(func(val T9, err error) {
		res9 = val
		cb(err)
	})
	t10.Subscribe(func(val T10, err error) {
		res10 = val
		cb(err)
	})

	return p.Future()
}

// Of12 waits for 12 Futures of unrelated types and resolves with a Tuple12.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of12[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2], t3 *future.Future[T3], t4 *future.Future[T4], t5 *future.Future[T5], t6 *future.Future[T6], t7 *future.Future[T7], t8 *future.Future[T8], t9 *future.Future[T9], t10 *future.Future[T10], t11 *future.Future[T11]) *future.Future[Tuple12[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]] {
	var done uint32
	p := future.NewPromise[Tuple12[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]]()
	c := int32(12)

	var res0 T0
	var res1 T1
	var res2 T2
	var res3 T3
	var res4 T4
	var res5 T5
	var res6 T6
	var res7 T7
	var res8 T8
	var res9 T9
	var res10 T10
	var res11 T11

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple12[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple12[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]{res0, res1, res2, res3, res4, res5, res6, res7, res8, res9, res10, res11}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})
	t3.Subscribe(func(val T3, err error) {
		res3 = val
		cb(err)
	})
	t4.Subscribe(func(val T4, err error) {
		res4 = val
		cb(err)
	})
	t5.Subscribe(func(val T5, err error) {
		res5 = val
		cb(err)
	})
	t6.Subscribe(func(val T6, err error) {
		res6 = val
		cb(err)
	})
	t7.Subscribe(func(val T7, err error) {
		res7 = val
		cb(err)
	})
	t8.Subscribe(func(val T8, err error) {
		res8 = val
		cb(err)
	})
	t9.Subscribe(func(val T9, err error) {
		res9 = val
		cb(err)
	})
	t10.Subscribe(func(val T10, err error) {
		res10 = val
		cb(err)
	})
	t11.Subscribe(func(val T11, err error) {
		res11 = val
		cb(err)
	})

	return p.Future()
}

// Of13 waits for 13 Futures of unrelated types and resolves with a Tuple13.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of13[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2], t3 *future.Future[T3], t4 *future.Future[T4], t5 *future.Future[T5], t6 *future.Future[T6], t7 *future.Future[T7], t8 *future.Future[T8], t9 *future.Future[T9], t10 *future.Future[T10], t11 *future.Future[T11], t12 *future.Future[T12]) *future.Future[Tuple13[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]] {
	var done uint32
	p := future.NewPromise[Tuple13[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]]()
	c := int32(13)

	var res0 T0
	var res1 T1
	var res2 T2
	var res3 T3
	var res4 T4
	var res5 T5
	var res6 T6
	var res7 T7
	var res8 T8
	var res9 T9
	var res10 T10
	var res11 T11
	var res12 T12

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple13[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple13[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{res0, res1, res2, res3, res4, res5, res6, res7, res8, res9, res10, res11, res12}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})
	t3.Subscribe(func(val T3, err error) {
		res3 = val
		cb(err)
	})
	t4.Subscribe(func(val T4, err error) {
		res4 = val
		cb(err)
	})
	t5.Subscribe(func(val T5, err error) {
		res5 = val
		cb(err)
	})
	t6.Subscribe(func(val T6, err error) {
		res6 = val
		cb(err)
	})
	t7.Subscribe(func(val T7, err error) {
		res7 = val
		cb(err)
	})
	t8.Subscribe(func(val T8, err error) {
		res8 = val
		cb(err)
	})
	t9.Subscribe(func(val T9, err error) {
		res9 = val
		cb(err)
	})
	t10.Subscribe(func(val T10, err error) {
		res10 = val
		cb(err)
	})
	t11.Subscribe(func(val T11, err error) {
		res11 = val
		cb(err)
	})
	t12.Subscribe(func(val T12, err error) {
		res12 = val
		cb(err)
	})

	return p.Future()
}

// Of14 waits for 14 Futures of unrelated types and resolves with a Tuple14.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of14[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2], t3 *future.Future[T3], t4 *future.Future[T4], t5 *future.Future[T5], t6 *future.Future[T6], t7 *future.Future[T7], t8 *future.Future[T8], t9 *future.Future[T9], t10 *future.Future[T10], t11 *future.Future[T11], t12 *future.Future[T12], t13 *future.Future[T13]) *future.Future[Tuple14[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]] {
	var done uint32
	p := future.NewPromise[Tuple14[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]]()
	c := int32(14)

	var res0 T0
	var res1 T1
	var res2 T2
	var res3 T3
	var res4 T4
	var res5 T5
	var res6 T6
	var res7 T7
	var res8 T8
	var res9 T9
	var res10 T10
	var res11 T11
	var res12 T12
	var res13 T13

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple14[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple14[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]{res0, res1, res2, res3, res4, res5, res6, res7, res8, res9, res10, res11, res12, res13}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})
	t3.Subscribe(func(val T3, err error) {
		res3 = val
		cb(err)
	})
	t4.Subscribe(func(val T4, err error) {
		res4 = val
		cb(err)
	})
	t5.Subscribe(func(val T5, err error) {
		res5 = val
		cb(err)
	})
	t6.Subscribe(func(val T6, err error) {
		res6 = val
		cb(err)
	})
	t7.Subscribe(func(val T7, err error) {
		res7 = val
		cb(err)
	})
	t8.Subscribe(func(val T8, err error) {
		res8 = val
		cb(err)
	})
	t9.Subscribe(func(val T9, err error) {
		res9 = val
		cb(err)
	})
	t10.Subscribe(func(val T10, err error) {
		res10 = val
		cb(err)
	})
	t11.Subscribe(func(val T11, err error) {
		res11 = val
		cb(err)
	})
	t12.Subscribe(func(val T12, err error) {
		res12 = val
		cb(err)
	})
	t13.Subscribe(func(val T13, err error) {
		res13 = val
		cb(err)
	})

	return p.Future()
}

// Of15 waits for 15 Futures of unrelated types and resolves with a Tuple15.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of15[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2], t3 *future.Future[T3], t4 *future.Future[T4], t5 *future.Future[T5], t6 *future.Future[T6], t7 *future.Future[T7], t8 *future.Future[T8], t9 *future.Future[T9], t10 *future.Future[T10], t11 *future.Future[T11], t12 *future.Future[T12], t13 *future.Future[T13], t14 *future.Future[T14]) *future.Future[Tuple15[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]] {
	var done uint32
	p := future.NewPromise[Tuple15[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]]()
	c := int32(15)

	var res0 T0
	var res1 T1
	var res2 T2
	var res3 T3
	var res4 T4
	var res5 T5
	var res6 T6
	var res7 T7
	var res8 T8
	var res9 T9
	var res10 T10
	var res11 T11
	var res12 T12
	var res13 T13
	var res14 T14

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple15[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple15[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]{res0, res1, res2, res3, res4, res5, res6, res7, res8, res9, res10, res11, res12, res13, res14}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})
	t3.Subscribe(func(val T3, err error) {
		res3 = val
		cb(err)
	})
	t4.Subscribe(func(val T4, err error) {
		res4 = val
		cb(err)
	})
	t5.Subscribe(func(val T5, err error) {
		res5 = val
		cb(err)
	})
	t6.Subscribe(func(val T6, err error) {
		res6 = val
		cb(err)
	})
	t7.Subscribe(func(val T7, err error) {
		res7 = val
		cb(err)
	})
	t8.Subscribe(func(val T8, err error) {
		res8 = val
		cb(err)
	})
	t9.Subscribe(func(val T9, err error) {
		res9 = val
		cb(err)
	})
	t10.Subscribe(func(val T10, err error) {
		res10 = val
		cb(err)
	})
	t11.Subscribe(func(val T11, err error) {
		res11 = val
		cb(err)
	})
	t12.Subscribe(func(val T12, err error) {
		res12 = val
		cb(err)
	})
	t13.Subscribe(func(val T13, err error) {
		res13 = val
		cb(err)
	})
	t14.Subscribe(func(val T14, err error) {
		res14 = val
		cb(err)
	})

	return p.Future()
}

// Of16 waits for 16 Futures of unrelated types and resolves with a Tuple16.
//
// It fails fast: the first error observed is propagated and the tuple is left
// at its zero value. Futures that are still pending are not cancelled.
func Of16[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 any](t0 *future.Future[T0], t1 *future.Future[T1], t2 *future.Future[T2], t3 *future.Future[T3], t4 *future.Future[T4], t5 *future.Future[T5], t6 *future.Future[T6], t7 *future.Future[T7], t8 *future.Future[T8], t9 *future.Future[T9], t10 *future.Future[T10], t11 *future.Future[T11], t12 *future.Future[T12], t13 *future.Future[T13], t14 *future.Future[T14], t15 *future.Future[T15]) *future.Future[Tuple16[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]] {
	var done uint32
	p := future.NewPromise[Tuple16[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]]()
	c := int32(16)

	var res0 T0
	var res1 T1
	var res2 T2
	var res3 T3
	var res4 T4
	var res5 T5
	var res6 T6
	var res7 T7
	var res8 T8
	var res9 T9
	var res10 T10
	var res11 T11
	var res12 T12
	var res13 T13
	var res14 T14
	var res15 T15

	cb := func(err error) {
		if err != nil {
			if atomic.CompareAndSwapUint32(&done, 0, 1) {
				p.SetSafety(Tuple16[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]{}, err)
			}
		} else {
			if atomic.AddInt32(&c, -1) == 0 {
				p.SetSafety(Tuple16[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]{res0, res1, res2, res3, res4, res5, res6, res7, res8, res9, res10, res11, res12, res13, res14, res15}, nil)
			}
		}
	}
	t0.Subscribe(func(val T0, err error) {
		res0 = val
		cb(err)
	})
	t1.Subscribe(func(val T1, err error) {
		res1 = val
		cb(err)
	})
	t2.Subscribe(func(val T2, err error) {
		res2 = val
		cb(err)
	})
	t3.Subscribe(func(val T3, err error) {
		res3 = val
		cb(err)
	})
	t4.Subscribe(func(val T4, err error) {
		res4 = val
		cb(err)
	})
	t5.Subscribe(func(val T5, err error) {
		res5 = val
		cb(err)
	})
	t6.Subscribe(func(val T6, err error) {
		res6 = val
		cb(err)
	})
	t7.Subscribe(func(val T7, err error) {
		res7 = val
		cb(err)
	})
	t8.Subscribe(func(val T8, err error) {
		res8 = val
		cb(err)
	})
	t9.Subscribe(func(val T9, err error) {
		res9 = val
		cb(err)
	})
	t10.Subscribe(func(val T10, err error) {
		res10 = val
		cb(err)
	})
	t11.Subscribe(func(val T11, err error) {
		res11 = val
		cb(err)
	})
	t12.Subscribe(func(val T12, err error) {
		res12 = val
		cb(err)
	})
	t13.Subscribe(func(val T13, err error) {
		res13 = val
		cb(err)
	})
	t14.Subscribe(func(val T14, err error) {
		res14 = val
		cb(err)
	})
	t15.Subscribe(func(val T15, err error) {
		res15 = val
		cb(err)
	})

	return p.Future()
}
